// This is code generated by hgen. DO NOT EDIT!!!
// hgen version: v0.1.5
// source: string.gfj

#ifndef __string_RPCH_CLIENT_H_
#define __string_RPCH_CLIENT_H_

#include <stdint.h>
#include "client.h"


char* string_toupper(char*, client_t*);
char* string_tolower(char*, client_t*);
char* string_concat(char*, char*, client_t*);
int32_t string_atoi(char*, client_t*);

#endif