// This is code generated by hgen. DO NOT EDIT!!!
// hgen version: v0.1.7
// source: math.gfj

#ifndef __math_RPCH_SERVER_H_
#define __math_RPCH_SERVER_H_

#include <stdint.h>
#include "error.h"
#include "server.h"

struct Quotient;
struct TwoNum;

struct Quotient{		
	uint64_t Quo;		
	uint64_t Rem;
};

struct TwoNum{		
	int32_t A;		
	int32_t B;
};

struct Quotient* Quotient_create();

struct Quotient* Quotient_clone(struct Quotient*);
struct TwoNum* TwoNum_clone(struct TwoNum*);

// server should implement following functions for service: Math
//**********************************************************
uint32_t Math_Add(uint32_t, uint32_t, error_t*);
int32_t Math_Sub(int32_t, int32_t, error_t*);
int32_t Math_Multiply(struct TwoNum*, error_t*);
struct Quotient* Math_Divide(uint64_t, uint64_t, error_t*);
//**********************************************************
void register_Math_service(server_t*);

#endif