// This is code generated by hgen. DO NOT EDIT!!!
// hgen version: v0.1.7
// source: math.gfj

#ifndef __math_RPCH_CLIENT_H_
#define __math_RPCH_CLIENT_H_

#include <stdint.h>
#include "client.h"

struct Quotient;
struct TwoNum;

struct Quotient{		
	uint64_t Quo;		
	uint64_t Rem;
};

struct TwoNum{		
	int32_t A;		
	int32_t B;
};

void Quotient_delete(struct Quotient*);

uint32_t Math_Add(uint32_t, uint32_t, client_t*);
int32_t Math_Sub(int32_t, int32_t, client_t*);
int32_t Math_Multiply(struct TwoNum*, client_t*);
struct Quotient* Math_Divide(uint64_t, uint64_t, client_t*);

#endif