// This is code generated by hgen. DO NOT EDIT!!!
// hgen version: v0.1.5
// source: book.gfj

#ifndef __book_RPCH_SERVER_H_
#define __book_RPCH_SERVER_H_

#include <stdint.h>
#include "error.h"
#include "server.h"

struct Account;
struct Book;
struct Price;

struct Account{		
	char* userName;		
	float balance;
};

struct Book{		
	struct Price* price;		
	char* name;
};

struct Price{		
	char* unit;		
	float num;
};

struct Book* Book_create();
struct Account* Account_create();

// server should implement following functions for service: bookMarket
//**********************************************************
struct Book* bookMarket_getBook(char*, error_t*);
struct Account* bookMarket_consume(struct Book*, struct Account*, error_t*);
void bookMarket_updateBookPrice(char*, struct Price*, error_t*);
void bookMarket_shelve(struct Book*, error_t*);
//**********************************************************
void register_bookMarket_service(server_t*);

#endif